//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставщик.
    /// </summary>
    // *** Start programmer edit section *** (Поставщик CustomAttributes)

    // *** End programmer edit section *** (Поставщик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставщикE", new string[] {
            "Телефон as \'Телефон\'",
            "Поставщик as \'Поставщик\'"})]
    [View("ПоставщикL", new string[] {
            "Телефон as \'Телефон\'",
            "Поставщик as \'Поставщик\'"})]
    public class Поставщик : ICSSoft.STORMNET.DataObject
    {
        
        private int fТелефон;
        
        private string fПоставщик;
        
        // *** Start programmer edit section *** (Поставщик CustomMembers)

        // *** End programmer edit section *** (Поставщик CustomMembers)

        
        /// <summary>
        /// Поставщик.
        /// </summary>
        // *** Start programmer edit section *** (Поставщик.Поставщик CustomAttributes)

        // *** End programmer edit section *** (Поставщик.Поставщик CustomAttributes)
        [StrLen(255)]
        public virtual string Поставщик
        {
            get
            {
                // *** Start programmer edit section *** (Поставщик.Поставщик Get start)

                // *** End programmer edit section *** (Поставщик.Поставщик Get start)
                string result = this.fПоставщик;
                // *** Start programmer edit section *** (Поставщик.Поставщик Get end)

                // *** End programmer edit section *** (Поставщик.Поставщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщик.Поставщик Set start)

                // *** End programmer edit section *** (Поставщик.Поставщик Set start)
                this.fПоставщик = value;
                // *** Start programmer edit section *** (Поставщик.Поставщик Set end)

                // *** End programmer edit section *** (Поставщик.Поставщик Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Поставщик.Телефон CustomAttributes)

        // *** End programmer edit section *** (Поставщик.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Поставщик.Телефон Get start)

                // *** End programmer edit section *** (Поставщик.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Поставщик.Телефон Get end)

                // *** End programmer edit section *** (Поставщик.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщик.Телефон Set start)

                // *** End programmer edit section *** (Поставщик.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Поставщик.Телефон Set end)

                // *** End programmer edit section *** (Поставщик.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставщикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикE", typeof(IIS.1.Поставщик));
                }
            }
            
            /// <summary>
            /// "ПоставщикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикL", typeof(IIS.1.Поставщик));
                }
            }
        }
    }
}
