//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип доставки.
    /// </summary>
    // *** Start programmer edit section *** (ТипДоставки CustomAttributes)

    // *** End programmer edit section *** (ТипДоставки CustomAttributes)
    public enum ТипДоставки
    {
        
        // *** Start programmer edit section *** (ТипДоставки.Самовывоз CustomAttributes)

        // *** End programmer edit section *** (ТипДоставки.Самовывоз CustomAttributes)
        Самовывоз,
        
        // *** Start programmer edit section *** (ТипДоставки.Курьер CustomAttributes)

        // *** End programmer edit section *** (ТипДоставки.Курьер CustomAttributes)
        Курьер,
    }
}
